version: '3.1'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_kanban'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_DB}
      - MONGO_DATA_DIR=/docker/data/db
      - MONGO_LOG_DIR=/docker/data/db/logs
    volumes:
      - ./docker/data/db:/data/db
    ports:
      - "27017:27017"
  cache:
    image: 'redis'
    container_name: 'redis_kanban'
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports: 
      - '6379:6379'