version: '3.0'

services:
  database:
    container_name: 'kanban_mongo_dev'
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_DB}
      - MONGO_DATA_DIR=/docker/data/db
      - MONGO_LOG_DIR=/docker/data/db/logs
    extends:
      file: docker-compose.base.yml
      service: database
    volumes:
      - ./initdb.dev.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - ./../docker/dev/db:/data/db
    working_dir: ${PWD}/docker/data/db/dev
    env_file:
      - ./../envs/.dev.env
    ports:
      - "27017:27017"
  cache:
    container_name: 'redis_mongo_dev'
    extends:
      file: docker-compose.base.yml
      service: cache
    env_file:
      - ./../envs/.dev.env
    ports:
      - '6379:6379'