version: '3.0'
services:
  database:
    container_name: 'kanban_mongo_test'
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_DB}
      - MONGO_DATA_DIR=/docker/data/db
      - MONGO_LOG_DIR=/docker/data/db/logs
    extends:
      file: docker-compose.base.yml
      service: database
    volumes:
      - ./initdb.test.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - ./../docker/test/db:/data/db
    working_dir: ${PWD}/docker/data/db/test
    env_file:
      - ./../envs/.test.env
    ports:
      - "27018:27017"
  cache:
    container_name: 'kanban_redis_test'
    extends:
      file: docker-compose.base.yml
      service: cache
    env_file:
      - ./../envs/.test.env
    ports:
      - '6380:6379'